# Generated by Django 2.0.13 on 2019-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190628_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=256, verbose_name='用户名')),
                ('password', models.CharField(max_length=126, verbose_name='密码')),
                ('email', models.CharField(max_length=256, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
