# Generated by Django 2.0.13 on 2019-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_comment',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
